"""add_workflow_schedules_table

Revision ID: 805bb1baa513
Revises: d28f2004b072
Create Date: 2025-05-17 23:39:15.440057

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805bb1baa513'
down_revision = 'd28f2004b072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_schedules',
        sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', models.types.StringUUID(), nullable=False),
        sa.Column('app_id', models.types.StringUUID(), nullable=False),
        sa.Column('workflow_id', models.types.StringUUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('cron_expression', sa.String(length=255), nullable=False),
        sa.Column('timezone', sa.String(length=255), nullable=False),
        sa.Column('inputs', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
        sa.Column('created_by', models.types.StringUUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), onupdate=sa.text('now()'), nullable=False),
        sa.Column('last_run_at', sa.DateTime(), nullable=True),
        sa.Column('next_run_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id', name='workflow_schedule_pkey')
    )
    op.create_index('workflow_schedule_app_idx', 'workflow_schedules', ['tenant_id', 'app_id'], unique=False)
    op.create_index('workflow_schedule_workflow_idx', 'workflow_schedules', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('workflow_schedule_workflow_idx', table_name='workflow_schedules')
    op.drop_index('workflow_schedule_app_idx', table_name='workflow_schedules')
    op.drop_table('workflow_schedules')
    # ### end Alembic commands ###
